### ISSUE TITLE
[Feat] 종류별 상품 목록 조회

### ISSUE THREAD

**Issue by hongsy521** [coool-developers/hot-item-collector#10]
**🌟 Issue : Feature**
팔로우한 사용자 상품 조회, 좋아요한 상품 조회, Hot 10 Item, 판매상태에 따른 상품 조회

**Description**
내가 팔로우한 사람들의 상품 목록 조회
내가 좋아요한 상품 목록 조회
`좋아요수가 많은 상품 순`으로 10개 조회
`판매중/판매완료`로 나눈 상품 목록 조회

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 팔로우한 사용자 상품 조회
- [x] 좋아요한 상품 조회
- [x] Hot 10 Item
- [x] 판매상태에 따른 상품 조회

**Reference(Optional)**
