### ISSUE TITLE
[Fix] Follow부분 코드 수정

### ISSUE THREAD

**Issue by WonGi-Kim** [coool-developers/hot-item-collector#30]
**🌟 Issue : Refactor**
Follow부분 코드 수정

**Description**
피드백 받은 내용으로 Follow부분 코드를 수정합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 엔티티 내부 생성자 부분 코드 수정
- [x] FollowService 내부 UserRepository 관련 내용 수정
- [x] FollowSerivce 내부 @ Transactional 추가

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
