### ISSUE TITLE
[Feat] MainPage api 연결

### ISSUE THREAD

**Issue by hongsy521** [coool-developers/hot-item-collector#46]
**🌟 Issue : Feature**
MainPage api 연결

**Description**
MainPage api 연결

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] top 10 상품 목록 
- [x] 신제품 상품 목록
- [x] 팔로우 사용자 상품 목록
- [ ] 상품 상세페이지
- [x] 상품 더보기 (신제품/팔로우)

**Reference(Optional)**
