### ISSUE TITLE
[Refactor] 마이프로필 부분에서 내가 구매한 상품 api 연결

### ISSUE THREAD

**Issue by sujeongmoon** [coool-developers/hot-item-collector#79]
**🌟 Issue : Feature**
마이프로필 부분에서 내가 구매한 상품 api 연결
페이지네이션

**Description**

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] orderController - getOrdersAllByBuyer 메서드 수정
- [x] 마이프로필에서 4개씩 주문 완료한 상품 보여지게
- [x] 주문관리 내역 - 주문 완료한 시점 나오도록
- [x] 구매한 상품 목록 에러 해결
- [x] 구매한 상품 목록에서 상품 이름 누르면 해당 상세페이지로 이동 -> 해당 주문페이지로 이동
- [x] 남의 프로필 볼 때 페이지에서 ID 표시 -> 닉네임으로 변경

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
