### ISSUE TITLE
[Feat] 피드백 기반 코드 수정 - 서영

### ISSUE THREAD

**Issue by hongsy521** [coool-developers/hot-item-collector#84]
**🌟 Issue : Feature**
최종프로젝트 피드백 기반 코드 수정

**Description**
최종프로젝트 피드백 기반 코드 수정

**Todo**
- [ ] 하나의 API에서 정렬 조건을 여러 개 받아서 처리할 수 있지 않았을까요? 예를 들면 상품 검색, 판매 상태별 자신의 상품 목록 조회, 판매 상태별 다른 사용자의 판매상품 조회는 제가 판단했을 때, where 절 조건만 달라지는 것으로 보여 합칠 수 있을 것 같다는 생각이 듭니다.
- [ ] 또한, 목록 조회 API에 대해서, request params로 뭐가 들어가야 하는지 구체적으로 정의해주었으면 좋겠습니다.
- [ ] ERD에 사용자 테이블의 프로필 사진은 s3 경로를 의미하는 것 같은데, 만약 s3에서 생성된 경로가 255 글자를 넘어가면 어떻게 되나요? 255글자라면 충분히 넘어갈 수 있을 것 같아 질문드립니다.
- [ ] 프로젝트 아키텍처를 보니, 단일 서버로 운영되는 것으로 보입니다. 만약, 하나의 서버에 트래픽이 너무나도 많이 몰려 하나의 응답을 주기까지 시간이 너무나도 오래 걸린다고 했을 때 스케일 아웃을 고려했을까요? 고려했다면 어떤 식으로 구성했는지도 답변해주세요. 안 되어 있다면, 어떤 계획을 하고 있는지 답변해주세요.

**Reference(Optional)**
